### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by elwakka** [zmanowar/random-event-analytics#11]
Overlay gone.
All previous events gone.
Timer just keeps ticking to 5 minutes on side bar... when random events happen, nothing is logged.

**Comment by zmanowar** [comment]
Hello! Sorry for the issues.

Would you mind uploading your client log?
- Navigate to %userprofile%\.runelite\logs on Windows or $HOME/.runelite/logs on Linux and macOS.
- Upload the log file named `client.log`

Also if you look in your `.runelite/random-event-analytics` folder do you see a folder with your login name or are the subfolders all numbers? (You should see folders named with numbers).

Within those folders there'll be a `random-events.log` file that should contain all of your randoms.

In the plugin settings do you have "Enable Overlay" toggled?
Did this happen on multiple accounts?

There's a fix for a few issues (unrelated to this) currently being reviewed by the RL team that _might_ fix a few things.

**Comment by elwakka** [comment]
I'm using the rune launcher, but not a jagex account.

Only one account.
Yes, overlay is turned on.
Relogging / exiting does not do anything..

The log file just has the following line spammed over and over:

`2023-05-06 15:57:57 EDT [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NullPointerException: null
`

The random-events.log doesn't seem like it has updated in a week.

**Comment by zmanowar** [comment]
I wonder if it's a Rune launcher issue, I haven't tested the plugin through it yet. I'll download the launcher and see if I can replicate it in a few.

Id expect to see errors directly related to the plugin.

Is there anything above all of the null pointer errors?

You might try starting runelite in safemode:

> Launch RuneLite in safe mode using the following command:
```
"%localappdata%\runelite\runelite.exe" --safe-mode
```
(or by launching the Runelite (Configure) app - unsure how this works via the Rune launcher)

And renabling just Random Event Analytics, just to ensure no other plugin is the root cause.

There's also debug mode, which you can enable by passing in `--debug` similar to safe-mode. That would make the logs much more verbose and might shed some light.

**Comment by elwakka** [comment]
I'll try that when I get home.  I do know it was working before fine... just recently it broke, so I don't know if any changes were made to the live branch in Runelite.  I've always used the Jagex Launcher.

**Comment by zmanowar** [comment]
https://github.com/runelite/plugin-hub/pull/4309 was merged ~3 hours ago, would you mind restarting your client (if you've had it running) and checking if it's still broken?

Let me know, happy to take a look at logs as well.

**Comment by elwakka** [comment]
Seems to work now
