### ISSUE TITLE
Toggling plugin on and off removes history

### ISSUE THREAD

**Issue by samszotkowski** [zmanowar/random-event-analytics#7]
Just toggled it on and off in runelite settings and the history disappeared
![image](https://user-images.githubusercontent.com/94253934/236113319-ae621acc-7e90-4fc1-8198-0859a8017f46.png)

**Comment by zmanowar** [comment]
Added a commit (https://github.com/zmanowar/random-event-analytics/commit/39c6d6e54d3f8e67538f80156eabafebe7577ae7) that should fix this (among other issues) -- however the "Initial Login Countdown" will reset, not sure how I want to go about approaching that.

Ideally it would continue tracking, but there's not a _smooth_ way to do that since turning the plugin off removes the state. Probably writing to config, but there's a few wonky edge-cases.

With that commit I added some tech debt around the timetracker, will try to keep the second bug in mind when cleaning things up.

**Comment by zmanowar** [comment]
This should be fixed, feel free to re-open if not!
